name: New Ubuntu Base Version â›­

on:
  repository_dispatch:
    types:
      - new_base_images_requested
      - new_ubuntu_base_image_requested
  workflow_dispatch:
    inputs:
      repo_version:
        description: 'Repository version (e.g. 4.0.0)'
        required: true
        type: string

# Further reading:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch
# https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-repository-dispatch-event
# https://developer.github.com/webhooks/event-payloads/#repository_dispatch

jobs:
  build:
    name: "ðŸ›  Build jpellet/gameci-base"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Checkout latest release tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $LATEST_TAG

      #################
      #   Variables   #
      #################
      - name: Show hook input
        run: |
          echo "Event ${{ github.event.action || 'workflow_dispatch' }}"
          echo "jobId: ${{ github.event.client_payload.jobId || format('manual-{0}', github.run_id) }}"
          echo "repoVersion (full): ${{ github.event.client_payload.repoVersionFull || github.event.inputs.repo_version }}"
          echo "repoVersion (only minor and major): ${{ github.event.client_payload.repoVersionMinor || github.event.inputs.repo_version }}"
          echo "repoVersion (only major): ${{ github.event.client_payload.repoVersionMajor || github.event.inputs.repo_version }}"
      #############
      #   Setup   #
      #############
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check if image does not already exist
        run: |
          # Source: https://stackoverflow.com/a/39731444/3593896
          function docker_tag_exists() {
            curl --silent -f -lSL https://index.docker.io/v1/repositories/$1/tags/$2 > /dev/null
          }

          if docker_tag_exists jpellet/gameci-base ubuntu-${{ github.event.client_payload.repoVersionFull || github.event.inputs.repo_version }} ; then
            echo "Image already exists. Exiting."
            exit 1
          fi
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.event.client_payload.repoVersionFull }}-${{ runner.os }}-buildx-base-${{ github.sha }}
          restore-keys: |
            ${{ github.event.client_payload.repoVersionFull }}-${{ runner.os }}-buildx-base
            ${{ github.event.client_payload.repoVersionFull }}-${{ runner.os }}-buildx-
      ##################
      #   Base image   #
      ##################
      - name: Build and publish
        uses: docker/build-push-action@v5
        id: build_ubuntu_base_image
        with:
          file: ./images/ubuntu/base/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          tags: |
            jpellet/gameci-base:ubuntu-${{ github.event.client_payload.repoVersionFull || github.event.inputs.repo_version }}
            jpellet/gameci-base:${{ github.event.client_payload.repoVersionFull || github.event.inputs.repo_version }}
            jpellet/gameci-base:ubuntu-${{ github.event.client_payload.repoVersionMinor || github.event.inputs.repo_version }}
            jpellet/gameci-base:${{ github.event.client_payload.repoVersionMinor || github.event.inputs.repo_version }}
            jpellet/gameci-base:ubuntu-${{ github.event.client_payload.repoVersionMajor || github.event.inputs.repo_version }}
            jpellet/gameci-base:${{ github.event.client_payload.repoVersionMajor || github.event.inputs.repo_version }}
      - name: Inspect
        run: |
          docker buildx imagetools inspect jpellet/gameci-base:ubuntu-${{ github.event.client_payload.repoVersionFull || github.event.inputs.repo_version }}
      - name: Image digest
        run: echo ${{ steps.build_ubuntu_base_image.outputs.digest }}
      #################
      #   reporting   #
      #################
